title: "The Digital Spell"
email: contact@thedigitalspell.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Pazalla
paginate: 30
disqus: 'the-digital-spell'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-C20SHNW8KG

# Authors
authors:
  pazalla:
    name: Pazalla
    display_name: Pazalla
    avatar: 'assets/images/avatars/pazalla.png'
    email: pazalla@thedigitalspell.com
    web: https://www.thedigitalspell.com/
    twitter: https://twitter.com/thedigitalspell
    description: "Founder of The Digital Spell"

# Social
social:
  instagram: https://www.instagram.com/thedigitalspell
  twitter: https://twitter.com/thedigitalspell
  facebook: https://www.facebook.com/thedigitalspell

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives